# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e75441b61e66a1dcfb71d45b1e84e9a4631dd3d2dfb5936afed913685cb4f70d4896e02bae3f226ea7a69f4d3fff81ddba21b4c55a8d3ada32262c53ed615b8b

test:
  secret_key_base: 3ad2a2d19a756811b35aca0fb8f18947aab87a19713dee3110f8579e4d6939a371da7ed3a371809a3d42ed9c4d0fa56186bfb0d836d2f9129eb04a187e551ce3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
